spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mercado
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt:
  expiracao: 30
  chave-assinatura: YSBsZWJyZSDDqSBicmFuY2E=

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: appfile.log

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  profiles:
    active: dev

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

#####CONFIGURAÇÃO DE EMAIL############

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pedrorhamon16@gmail.com
    password: minha_senha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        ssl:
          enable: false
    test-connection: true
